volumes:
  demo_postgres_data:
    driver: local
services:
  app:
    image: hacken-test-app
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/csv_data_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - demo_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=csv_data_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres